### ISSUE TITLE
Can't work with dates

### ISSUE THREAD

**Issue by pauloandreget** [satyan/sugar#235]
I'm trying to work with dates but there seems to be a problem in the query. My class has a property:

private Date date;

I tried in every way to create the query but did not get an expected result in any attempt:

Entity.findWithQuery(Entity.class, "select * from Entity where date between '2013-1-1’ and '2013-12-31'")
Entity.find(Entity.class, "date >= date(?) AND date <= date(?)", "2013-1-1", "2013-12-31")

I have saved a record dated 2013-11-11, but never returns result.

**Comment by whoshuu** [comment]
Hey @pauloandreget, you're querying the date with a `String` of the year. This doesn't give you anything because `Date`s are actually handled internally as `Long`s. What you have to do is convert your `Date` into a `Long` by calling `.getTime()` on it. You can see how we do the conversion ourselves here: https://github.com/satyan/sugar/blob/9c04bdc16d00695571477c4af954ea6b2a7a2423/library/src/com/orm/util/ReflectionUtil.java#L85-L90

This brings up an interesting point though because handling dates this way might be a bit counterintuitive. SQLite does support actual date and time semantics and it would make sense to use those instead.

Let me know if you have any other issues on this matter.

**Comment by pauloandreget** [comment]
Exactly, it worked that way. Thank you for the explanation!
