### ISSUE TITLE
Do i need to include progurad?

### ISSUE THREAD

**Issue by dhrumit123** [satyan/sugar#280]
Is it mandatory to include proguard while publishing app to the play store ?

**Comment by whoshuu** [comment]
I think there are some proguard settings you have to configure in order to get sugar to play nicely with your app. I'm not sure what the play store's policy is on proguard. If anyone else has any idea, please chime in.

Otherwise, I think this issue is outside the scope of sugar, so I'm going to mark this for closing. Thanks @dhrumit123 for bringing it up.
