### ISSUE TITLE
How to use SugarTransactionHelper?

### ISSUE THREAD

**Issue by daybson** [satyan/sugar#433]
I can't find any example about how to use transactions with sugar orm.

**Comment by dnalves** [comment]
```
SugarTransactionHelper.doInTransaction(new SugarTransactionHelper.Callback() {
    @Override
     public void manipulateInTransaction() {
          // The code that you want to be executed inside the same transaction goes here :)
     }
});
```

**Comment by dmansurov83** [comment]
How I can throw Exception in manipulateInTransaction()?
I have to remove the linked file in transaction.
```
File f = new File(filename);
if (!f.delete()) throw new Exception("Cant delete file");
```
Android Studio shows me Error:(39, 42) error: unreported exception Exception; must be caught or declared to be thrown

**Comment by sibeliusseraphini** [comment]
@dmansurov83 could you provide a PR for that?

Maybe you could solve your problem without throwing an exception

**Comment by dmansurov83** [comment]
I solve by own TransactionHelper with transaction result:
```
package com.orm;

import android.database.sqlite.SQLiteDatabase;
import android.util.Log;

public class MyTransactionHelper {

    public static boolean doInTransaction(MyTransactionHelper.Callback callback) {
        SQLiteDatabase database = SugarContext.getSugarContext().getSugarDb().getDB();
        database.beginTransaction();
        boolean result = false;
        try {
            Log.d(SugarTransactionHelper.class.getSimpleName(),
                    "Callback executing within transaction");
            callback.manipulateInTransaction();
            database.setTransactionSuccessful();
            Log.d(SugarTransactionHelper.class.getSimpleName(),
                    "Callback successfully executed within transaction");
            result = true;
        } catch (Throwable e) {
            Log.d(SugarTransactionHelper.class.getSimpleName(),
                    "Could execute callback within transaction", e);
            result = false;
        } finally {
            database.endTransaction();
        }
        return result;
    }

    public static interface Callback {
        void manipulateInTransaction() throws Exception;
    }
}
```

**Comment by abegosum** [comment]
I'm seeing the same issue here, and I only see that someone has rewritten the SugarTransactionClass helper to fix it.  

The problem seems to be that, as written, there's no way to throw an exception in an overriden version of manipulateInTransaction because it declares nothing as thrown.  So, no matter what happens in your callback's manipulateInTransaction method, setTransactionSuccessful will ALWAYS be called, because no overriden manipulateInTransaction can throw an exception that would bubble up to this level.

dmansurov83's solution of adding `throws Exception` to your declaration solves the issue, though the actual API should probably be changed to `throws Throwable` to match the generic catch statement.

I see this issue is closed; but, will this change ever be implemented in the library?  I don't see dmansurov83's fix in the master branch.
