### ISSUE TITLE
where column like %?%

### ISSUE THREAD

**Issue by BoldijarPaul** [satyan/sugar#599]
How can I do a query for a text like

select * from table where name like %oh%

I'm getting error if i use %?%

**Comment by cutiko** [comment]
I want to do the same, @BoldijarPaul if you did can you give us a hint?

**Comment by cutiko** [comment]
Greetings

I just handle to do it by this way:
`List<YourClass> foundings = YourClass.find(YourClass.class, "name LIKE ?", "Your exact name");`

The problem is, if it is not the exact name, it doesnt work. By example, if it is the first 3 letter, or maybe the second word, it wont work it has to be exactly the "name"

**Comment by cutiko** [comment]
Figure it out how to do it here https://github.com/satyan/sugar/issues/611

**Comment by BoldijarPaul** [comment]
@cutiko  so we need to put the '%' symbol in the argument?

**Comment by cutiko** [comment]
@BoldijarPaul yes,  look at my example, hope to help
