### ISSUE TITLE
No such table exceptions

### ISSUE THREAD

**Issue by mrshll1001** [satyan/sugar#75]
Even though I've explicitly called the .save() method on my subclass of SugarRecord (Exercise) when the database is created I'm getting errors when querying and there's no such table exceptions associated with the class.

**Comment by idemax** [comment]
Create a empty constructor if you created one with arguments. Works to me after I cleared cache of app.

**Comment by exadeci** [comment]
I tried it all still the same error -_-

**Comment by idemax** [comment]
What error @exadeci ? And please paste you class too.

**Comment by exadeci** [comment]
@idemax The error was "No such table" but I created a new package for my models and it worked :)

**Comment by carlochess** [comment]
incrementing my database version in the manifest file work for me, also making a public constructor with no parameters.

**Comment by TekYin** [comment]
I got the same problem. I already following the "getting started" guide.. after searching for answer, I figured it by putting my package name of my classes of SugarRecord on "DOMAIN_PACKAGE_NAME"

**Comment by drmanhadan** [comment]
Please show what creating the constructor would look like

**Comment by whoshuu** [comment]
I believe many of these issues are a result of outdated documentation. When [1.4.0](https://github.com/satyan/sugar/milestones/1.4.0) is released, I'll be sure to update http://satyan.github.io/sugar to be as up to date and thorough as possible.

**Comment by OmarMahdoui** [comment]
I was having this error and i uninstalled my application and cleared cache and everything worked well .

**Comment by blackvvine** [comment]
the "no such table" error was solved for me when I correctly set the "DOMAIN_PACKAGE_NAME" meta data in AndroidManifest.xml
I simply used the exact package name of the database record classes.

**Comment by VKiril** [comment]
if you have done some changes into entity class, you must to change database version numbae

**Comment by voghDev** [comment]
I had the same issue on Sugar v1.3. 
Fixed it by leaving a default constructor without parameters for my class extending SugarRecord.

[...]
Exact error was: Error inserting LINE=89 NUM=0 SN=XYZQ  android.database.sqlite.SQLiteException: no such table: SERIALNUMBER (code 1): , while compiling: INSERT INTO [...]

**Comment by don-han** [comment]
If you are using `findWithQuery` and are manually entering a table name, you may get the exception that the table does not exist since your table name in Java class and your table in SQLite may differ. 

For example, if you have a table called `"ExampleTable"`, SQLite will create `"EXAMPLE_TABLE"`. To address this, use `StringUtil.toSQLName("TableName")`. Of course, the best way would be to use other methods in which you don't have to manually input the table names as detailed [here](http://satyan.github.io/sugar/query.html)

**Comment by fanadd** [comment]
Does it make sence to throw an exception if SugarRecord<> successor doesn't have a default constructor?

**Comment by blackvvine** [comment]
@fanadd I believe it does since SugarORM tries to instantiate it using reflection. It's not a code generator ORM.

**Comment by dnano91** [comment]
I still have this error (non such table) with 1.4 and the documentation is still very much outdated. tried all of the above (version number, domain package name, clearing cache/deleting app) nothing worked

**Comment by voghDev** [comment]
@dnano91  tried the empty constructor thing? see my comment above

**Comment by dnano91** [comment]
Yes, had an empty constructor anyway. That's why I forgot to mention it
Am 16.11.2015 12:55 schrieb "Olmo Gallegos" <notifications@github.com>:

**Comment by martijndebruijn** [comment]
I had the same error. It was caused by a wrong definition of the package name in the manifest file. I configured the root package of the app and not the package containing the model classes.

**Comment by moyheen** [comment]
I had the same error. I was using `findWithQuery` and manually entering a table name. I had to change my table name from `ExampleTable` to `example_Table` before the query worked.

**Comment by VKiril** [comment]
@moyheen  try to change database version from n to n+1 (for ex.)

**Comment by martijndebruijn** [comment]
When using Android Studio with Instant Run see issue https://github.com/satyan/sugar/issues/542

**Comment by firasalkafri** [comment]
Instant Run now works #559

**Comment by shashi2459** [comment]
I am getting same exception on my MotoG3- Marshmallow.
But same code runs on Kitkat tablet.
I m using 1.4 version.
What will be the specific reason on Marshmallow?

**Comment by JonatanSalas** [comment]
@shashi2459 if you use Android Studio it's because InstantRun generates own .dex files that Sugar don't take care, so when trying to deploy the app using InstantRun you don't get the tables generated.

**Comment by shashi2459** [comment]
ok....But the same code runs on Kitkat tablet.

**Comment by sibeliusseraphini** [comment]
Sugar takes care when Android Studio uses InstantRun, this pull #564 fix this

**Comment by JonatanSalas** [comment]
@sibeliusseraphini I refer to Sugar v1.5 not to the master branch.

**Comment by shashi2459** [comment]
@sibeliusseraphini I already tried v1.5 and the issue continues.

**Comment by JonatanSalas** [comment]
@shashi2459  the PR is in the master branch. Just configure your project to use the master and it will work.

**Comment by shashi2459** [comment]
@sibeliusseraphini how and where to configure it for Android Studio and Gradle?
Thanks.

**Comment by sibeliusseraphini** [comment]
@shashi2459 there is some instructions of using the master version with your project on README

**Comment by mattisback** [comment]
Had the same problem - turned out to be a problem with instant-run. 
Didn't want to switch to master (using 1.5) so just disabled instant run.

**To disable Instant Run:**
Open the _Settings or Preferences_ dialog.
Navigate to _Build, Execution, Deployment_ > _Instant Run_.
Uncheck the box next to _Enable Instant Run_.

**Comment by uzbit** [comment]
The suggestion of changing ExampleTable to example_Table in a findWithQuery suggested by @moyheen worked for me. This is not terribly encouraging since it was working with EXAMPLE_TABLE before I upgraded Android Studio to 2.0 and SDK to 23.0.3, Sugar ORM from 1.3 to (tried 1.4 and now on 1.5, both of which didn't work with the old table names).

**Comment by martijndebruijn** [comment]
I switch InstantRun off when I know Sugar has to create/modify tables. After the table DDL actions you can enable InstantRun again.

**Comment by truefedex** [comment]
Please, add instant run patches to release version - on new Android studio any demos not working without it.

**Comment by sibelius** [comment]
@truefedex you can use master version, just follow readme instructions

**Comment by augustosalazar** [comment]
Hi, it is not working for me using "com.github.satyan:sugar:1.4".

**Comment by augustosalazar** [comment]
Not working using compile 'com.github.satyan:sugar:1.4'

public class Data extends SugarRecord {

    String data1;
    String data2;

    public Data() {
    }

    public Data(String data1, String data2) {
        super();
        this.data1 = data1;
        this.data2 = data2;
    }

**Comment by fomojola** [comment]
If you're using 1.5, I've found that I have to give the library a bit of a kick to get it started. If you do

    adb logcat -s Sugar:*

and you don't see something like this:

    I/Sugar   (12467): domain class : Event
    I/Sugar   (12467): Create table if not exists 
    D/Sugar   (12467): Fetching properties
    I/Sugar   (12467): Creating table EVENT

Then try modifying your onCreate() in your App to look like this:

```
public void onCreate()
    {
        super.onCreate();

        // cheating: this forces Sugar to create or upgrade the DB
        new SugarDb(this).getDB().close();
    }
```

Suboptimal, but I found that this forces the database tables to be created (once you are sure you have all the required constructors/annotations setup right).

One potential improvement to the logging would be logging verification failures: i.e. whenever the ReflectionUtil retrieves a class that SHOULD be a candidate but fails it because it is missing an annotation or a required constructor make that an explicit log statement.
